### ISSUE TITLE
Movement of Robot

### ISSUE THREAD

**Issue by KSatsujin** [FRC7540/WolfBot2023#1]
## Summary

Robot must be able to move forwards, backwards, left, right, and rotate.

## Context

- Mecanum Drive Base
- Use XBOX Controller or Flight stick
- Strafing required
- Variable speed required
- Dampening required
- Code must work for both autonomous AND Teleop
- Controls MUST be documented

## Acceptance Criteria

- Driving accepts user input
- Controls are documented
- Must be able to strafe and turn
- Must have multiple speed modes (fine control and full speed)
- Robot does not jerk around

**Comment by Theinatorinator** [comment]
Can I get more clarification on the "Dampening required?" What exactly do we mean by that?

**Comment by KSatsujin** [comment]
Sorry, but who is this?

Anyway, the dampening references slew rate limiting for controls, making it
to where you can't switch directions fast enough to make the motors jerk
around. It's already implemented, and needs to be merged. I'm working on a
pull request now.
